###############################################################################
#                          Generated on phpdocker.io                          #
#
# Generic instructions: docker-compose up -d
#
# webDiplomacy instructions:
# Run composer update in the source root folder to create the vendor folder 
# which contains the required PHP dependencies.
# Check http://localhost:43000/gamemaster-entrypoint.txt ; once the server is ready you should see
# that gamemaster has started running. If there is an issue this is the best place to check.
# Register a user account, use http://localhost:43001 / mailhog to access the registration link
# Taking the registration link code and adding it to your webserver should give e.g.:
# http://localhost:43000/register.php?emailToken=9513e6f6%7C1665482821%7Ctest%40test.com
# Complete filling the registration form
# Go to http://localhost:43000/gamemaster.php?gameMasterSecret= to set self as admin
# Go to http://localhost:43000/admincp.php?tab=Control%20Panel and Toggle maintenance, 
# Clear variant caches, and Update wD_VariantInfo to ensure variant data is installed.
# Go to http://localhost:43000/datc.php and run batch test to test that processing is working
# Go to http://localhost:43000/admincp.php and disable maintenance mode
# Server is ready for dev work
#
###############################################################################
version: "3.1"
services:
  memcached:
    image: "memcached:alpine"
    container_name: webdiplomacy-memcached
    ports:
      - "11211"

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "43001:8025"

  mariadb:
    image: "mariadb:10.6"
    container_name: "webdiplomacy-db"
    restart: always
    working_dir: /application
    volumes:
      - "./:/application"
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword123
      - MYSQL_DATABASE=webdiplomacy
      - MYSQL_USER=webdiplomacy
      - MYSQL_PASSWORD=mypassword123
    ports:
      - "43003:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT:-8080}:80
    environment:
      - PMA_ARBITRARY=1

  clickhouse:
    image: "yandex/clickhouse-server:latest"

  # This is necessary for doing live React dev for the new board, but isn't needed after doing a build. If the nginx config is changed to not redirect /beta/ to port 3000:
  webserver:
    image: "nginx:alpine"
    working_dir: /application
    volumes:
      - "./:/application"
      - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "${WEBDIP_PORT:-43000}:80"
    depends_on:
      - "php-fpm"
  beta:
    image: "node:16.15.1-alpine3.14"
    container_name: webdiplomacy-beta
    working_dir: /application
    volumes:
      - "./beta-src:/application"
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install &&
              npm run start"

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - "./:/application"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini"
    command: /bin/sh -c "install/gamemaster-entrypoint.sh > /application/gamemaster-entrypoint.txt"
    depends_on:
      - "mariadb"
    #environment:
    #    PHP_IDE_CONFIG: "serverName=Docker"
    #    XDEBUG_MODE: debug
    #    XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    #    XDEBUG_SESSION: 1

  webserver:
      image: 'nginx:alpine'
      working_dir: /application
      volumes:
          - './:/application'
          - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      ports:
          - '${WEBDIP_PORT:-43000}:80'

  soketi:
    container_name: "webdiplomacy-websocket"
    restart: unless-stopped
    image: "quay.io/soketi/soketi:1.0-16-debian"
    ports:
      - "${SOKETI_PORT:-6001}:6001"
      - "${SOKETI_METRICS_SERVER_PORT:-9601}:9601"
    environment:
      - SOKETI_DEBUG=${SOKETI_DEBUG:-1}
      - SOKETI_DEFAULT_APP_ID=${SOKETI_DEFAULT_APP_ID:-app-id}
      - SOKETI_DEFAULT_APP_KEY=${SOKETI_DEFAULT_APP_KEY:-app-key}
      - SOKETI_DEFAULT_APP_SECRET=${SOKETI_DEFAULT_APP_SECRET:-app-secret}
      - USER_AUTHENTICATION_TIMEOUT=${SOKETI_USER_AUTHENTICATION_TIMEOUT:-5000}
